### ISSUE TITLE
类别输出未经过softmax层

### ISSUE THREAD

**Issue by Willianwatch** [yjh0410/new-YOLOv1_PyTorch#3]
作者大大你好，感谢你提供的代码，对我帮助很大！
        我最近在做三维的目标检测，在修改代码之后发现类别部分的损失出现负数，搜索之后发现这是因为交叉熵损失的输入大于1，而经过检查也确实发现在网络的训练阶段，类别输出好像没有经过softmax层，这样是对的吗?

**Comment by yjh0410** [comment]
@Willianwatch 谢谢您的支持！
在训练过程中，类别输出没有经过softmax，是因为计算类别损失的函数`nn.CrossEntropy`函数里面自带了softmax的数学处理，无所我们在外部手动softmax。至于您说的损失出现了复数，一个可能的原因是标签出现了问题，建议检查一下类别的标签。

**Comment by Willianwatch** [comment]
@yjh0410 我去仔细看了pytorch的文档，确实你是对的。现在我的代码已经能够正确运行了，再次感谢！
